
Button_Settings:
  style:
    position: absolute
    top: 20
    left: 20
    width: 100
    height: 30
    backgroundColor: black
    borderRadius: 25
  children: [Text_Settings]
  on_touch:
    backgroundColor: rgb(50, 50, 50)
Text_Settings:
  style:
    color: gold
    fontSize: 15
    marginLeft: 20
    marginTop: 5
    fontFamily: product sans
  pos: 6
  len: 10